# Generated by Django 6.0.4 on 2026-05-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('integration_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=255)),
                ('on', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vexpenses_expense_type',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('on', models.BooleanField(default=True)),
                ('integration_id', models.CharField(blank=True, max_length=100, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vexpenses_project',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('integration_id', models.CharField(blank=True, max_length=100, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('company_id', models.IntegerField()),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('approval_flow_id', models.IntegerField(blank=True, null=True)),
                ('expense_limit_policy_id', models.IntegerField(blank=True, null=True)),
                ('user_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('agency', models.CharField(blank=True, max_length=50, null=True)),
                ('account', models.CharField(blank=True, max_length=50, null=True)),
                ('pix_key', models.CharField(blank=True, max_length=100, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('projects', models.ManyToManyField(blank=True, related_name='members', to='vexpensesinfos.project')),
            ],
            options={
                'db_table': 'vexpenses_team_member',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('expense_id', models.IntegerField(blank=True, null=True)),
                ('device_id', models.IntegerField(blank=True, null=True)),
                ('integration_id', models.CharField(blank=True, max_length=100, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mileage', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('expense_type_id', models.IntegerField(blank=True, null=True)),
                ('payment_method_id', models.IntegerField(blank=True, null=True)),
                ('paying_company_id', models.IntegerField(blank=True, null=True)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('receipt_url', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('validate', models.CharField(blank=True, max_length=10, null=True)),
                ('reimbursable', models.BooleanField(default=False)),
                ('observation', models.TextField(blank=True, null=True)),
                ('rejected', models.BooleanField(default=False)),
                ('on', models.BooleanField(default=True)),
                ('mileage_value', models.FloatField(blank=True, null=True)),
                ('original_currency_iso', models.CharField(blank=True, max_length=10, null=True)),
                ('exchange_rate', models.FloatField(blank=True, null=True)),
                ('converted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('converted_currency_iso', models.CharField(blank=True, max_length=10, null=True)),
                ('report_id', models.IntegerField(blank=True, null=True)),
                ('report_status', models.CharField(blank=True, max_length=50, null=True)),
                ('report_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='vexpensesinfos.teammember')),
            ],
            options={
                'db_table': 'vexpenses_expense',
            },
        ),
    ]
