# Generated by Django 4.2.30 on 2026-05-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vexpensesinfos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='apportionment_company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='apportionment_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
