# Generated by Django 6.0.4 on 2026-05-02 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conta_azul', models.CharField(max_length=36)),
                ('nome', models.CharField(max_length=80)),
                ('versao', models.IntegerField()),
                ('categoria_pai', models.CharField(blank=True, max_length=36, null=True)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10)),
                ('entrada_dre', models.CharField(max_length=50)),
                ('considera_custo_dre', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conta_azul', models.CharField(max_length=36)),
                ('codigo', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContaAzulToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conta_azul', models.CharField(max_length=36)),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('perfil', models.CharField(choices=[('CLIENTE', 'Cliente'), ('FORNECEDOR', 'Fornecedor'), ('TRANSPORTADOR', 'Transportador')], max_length=20)),
                ('tipo', models.CharField(choices=[('FISICA', 'Física'), ('JURIDICA', 'Jurídica')], max_length=10)),
                ('documento', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContaAReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conta_azul', models.CharField(max_length=36)),
                ('descricao', models.TextField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_vencimento', models.DateField()),
                ('data_competencia', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('data_alteracao', models.DateField(blank=True)),
                ('status', models.CharField(max_length=30)),
                ('status_traduzido', models.CharField(max_length=30)),
                ('pago', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nao_pago', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pessoa_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contaazulinfos.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='ContaAPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conta_azul', models.CharField(max_length=36)),
                ('descricao', models.TextField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_vencimento', models.DateField()),
                ('data_competencia', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('data_alteracao', models.DateField(blank=True)),
                ('status', models.CharField(max_length=30)),
                ('status_traduzido', models.CharField(max_length=30)),
                ('pago', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nao_pago', models.DecimalField(decimal_places=2, max_digits=15)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contaazulinfos.categoria')),
                ('centro_custo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contaazulinfos.centrocusto')),
                ('pessoa_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contaazulinfos.pessoa')),
            ],
        ),
    ]
