# Generated by Django 6.0.4 on 2026-05-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaazulinfos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocusto',
            name='codigo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
