# Generated by Django 6.0.4 on 2026-05-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaazulinfos', '0002_alter_centrocusto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='entrada_dre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
