# Generated by Django 6.0.4 on 2026-05-02 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaazulinfos', '0003_alter_categoria_entrada_dre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaareceber',
            name='pessoa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contaazulinfos.pessoa'),
        ),
    ]
