# Generated by Django 6.0.4 on 2026-05-02 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaazulinfos', '0004_alter_contaareceber_pessoa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaapagar',
            name='categoria_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contaazulinfos.categoria'),
        ),
        migrations.AlterField(
            model_name='contaapagar',
            name='centro_custo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contaazulinfos.centrocusto'),
        ),
        migrations.AlterField(
            model_name='contaapagar',
            name='pessoa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contaazulinfos.pessoa'),
        ),
    ]
