# Generated by Django 5.2.1 on 2026-05-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaazulinfos', '0008_alter_categoria_id_alter_centrocusto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
